name: s1mple
favicon: null
layout_spectrum: 0.2542
typography_spectrum: 0.80649
title: 'A s1mple site, for a s1mple man.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7847210997715592
  lightness: 0.4384756388608366
  saturation: 0.6731945581268519
  rhythmicContrast: 0.6868509887717664
purpose: []
